In [1]:
#https://www.cnblogs.com/hhxz/p/10626419.html
from sklearn.feature_extraction import DictVectorizer#转换工具，将list转换成为一个数组
from sklearn import preprocessing
from sklearn import tree #创建决策树
import numpy as np

In [2]:
# dataset: https://blog.csdn.net/leafage_m/article/details/79560791

dataSet = [
        # 1
        ['青绿', '蜷缩', '浊响', '清晰', '凹陷', '硬滑', '好瓜'],
        # 2
        ['乌黑', '蜷缩', '沉闷', '清晰', '凹陷', '硬滑', '好瓜'],
        # 3
        ['乌黑', '蜷缩', '浊响', '清晰', '凹陷', '硬滑', '好瓜'],
        # 4
        ['青绿', '蜷缩', '沉闷', '清晰', '凹陷', '硬滑', '好瓜'],
        # 5
        ['浅白', '蜷缩', '浊响', '清晰', '凹陷', '硬滑', '好瓜'],
        # 6
        ['青绿', '稍蜷', '浊响', '清晰', '稍凹', '软粘', '好瓜'],
        # 7
        ['乌黑', '稍蜷', '浊响', '稍糊', '稍凹', '软粘', '好瓜'],
        # 8
        ['乌黑', '稍蜷', '浊响', '清晰', '稍凹', '硬滑', '好瓜'],

        # ----------------------------------------------------
        # 9
        ['乌黑', '稍蜷', '沉闷', '稍糊', '稍凹', '硬滑', '坏瓜'],
        # 10
        ['青绿', '硬挺', '清脆', '清晰', '平坦', '软粘', '坏瓜'],
        # 11
        ['浅白', '硬挺', '清脆', '模糊', '平坦', '硬滑', '坏瓜'],
        # 12
        ['浅白', '蜷缩', '浊响', '模糊', '平坦', '软粘', '坏瓜'],
        # 13
        ['青绿', '稍蜷', '浊响', '稍糊', '凹陷', '硬滑', '坏瓜'],
        # 14
        ['浅白', '稍蜷', '沉闷', '稍糊', '凹陷', '硬滑', '坏瓜'],
        # 15
        ['乌黑', '稍蜷', '浊响', '清晰', '稍凹', '软粘', '坏瓜'],
        # 16
        ['浅白', '蜷缩', '浊响', '模糊', '平坦', '硬滑', '坏瓜'],
        # 17
        ['青绿', '蜷缩', '沉闷', '稍糊', '稍凹', '硬滑', '坏瓜']
    ]
labels = ['色泽', '根蒂', '敲击', '纹理', '脐部', '触感']

In [3]:
labelList = [] # 好瓜or坏瓜
featureList = [] # 对每只瓜记录具体的特征和特征值

for row in dataSet:
    labelList.append(row[-1])
    feature = {}
    for i in range(len(row)-1):
        feature[labels[i]] = row[i]
    featureList.append(feature)

In [16]:
featureList


[{'色泽': '青绿', '根蒂': '蜷缩', '敲击': '浊响', '纹理': '清晰', '脐部': '凹陷', '触感': '硬滑'},
 {'色泽': '乌黑', '根蒂': '蜷缩', '敲击': '沉闷', '纹理': '清晰', '脐部': '凹陷', '触感': '硬滑'},
 {'色泽': '乌黑', '根蒂': '蜷缩', '敲击': '浊响', '纹理': '清晰', '脐部': '凹陷', '触感': '硬滑'},
 {'色泽': '青绿', '根蒂': '蜷缩', '敲击': '沉闷', '纹理': '清晰', '脐部': '凹陷', '触感': '硬滑'},
 {'色泽': '浅白', '根蒂': '蜷缩', '敲击': '浊响', '纹理': '清晰', '脐部': '凹陷', '触感': '硬滑'},
 {'色泽': '青绿', '根蒂': '稍蜷', '敲击': '浊响', '纹理': '清晰', '脐部': '稍凹', '触感': '软粘'},
 {'色泽': '乌黑', '根蒂': '稍蜷', '敲击': '浊响', '纹理': '稍糊', '脐部': '稍凹', '触感': '软粘'},
 {'色泽': '乌黑', '根蒂': '稍蜷', '敲击': '浊响', '纹理': '清晰', '脐部': '稍凹', '触感': '硬滑'},
 {'色泽': '乌黑', '根蒂': '稍蜷', '敲击': '沉闷', '纹理': '稍糊', '脐部': '稍凹', '触感': '硬滑'},
 {'色泽': '青绿', '根蒂': '硬挺', '敲击': '清脆', '纹理': '清晰', '脐部': '平坦', '触感': '软粘'},
 {'色泽': '浅白', '根蒂': '硬挺', '敲击': '清脆', '纹理': '模糊', '脐部': '平坦', '触感': '硬滑'},
 {'色泽': '浅白', '根蒂': '蜷缩', '敲击': '浊响', '纹理': '模糊', '脐部': '平坦', '触感': '软粘'},
 {'色泽': '青绿', '根蒂': '稍蜷', '敲击': '浊响', '纹理': '稍糊', '脐部': '凹陷', '触感': '硬滑'},
 {'色泽': '浅白', '根蒂': '稍蜷',

In [5]:
#onehot 编码： https://www.cnblogs.com/ljhdo/archive/2019/07/30/10600702.html
# DictVectorizer()
vec = DictVectorizer()#获取转换对象
X = vec.fit_transform(featureList).toarray()#将特征值的list转变成为一个数组
print(X)
print(vec.get_feature_names())#获取特征所有的取值

[[0. 1. 0. 0. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0. 1. 1. 0.]
 [1. 0. 0. 0. 0. 1. 0. 1. 0. 1. 0. 0. 1. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0. 1. 0. 1. 0. 0. 1. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0. 1. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0. 1. 0. 1. 0. 0. 0. 1. 0. 1. 0.]
 [0. 1. 0. 0. 1. 0. 0. 1. 0. 0. 0. 1. 0. 0. 1. 0. 1.]
 [0. 1. 0. 0. 1. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0. 0. 1.]
 [0. 1. 0. 0. 1. 0. 0. 1. 0. 0. 0. 1. 1. 0. 0. 1. 0.]
 [1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0. 1. 0.]
 [0. 0. 1. 1. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 1. 0. 1.]
 [0. 0. 1. 1. 0. 0. 1. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 0. 1. 0. 0. 1.]
 [0. 1. 0. 0. 1. 0. 0. 0. 1. 1. 0. 0. 0. 0. 1. 1. 0.]
 [1. 0. 0. 0. 1. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 1. 0.]
 [0. 1. 0. 0. 1. 0. 0. 1. 0. 0. 0. 1. 1. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0.]
 [1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 1. 0. 0. 1. 1. 0.]]
['敲击=沉闷', '敲击=浊响', '敲击=清脆', '根蒂=硬挺', '根蒂=稍蜷', '根蒂=蜷缩', '纹理=模糊', '纹理=清晰', '纹理=稍糊',

In [6]:
lb = preprocessing.LabelBinarizer()
Y = lb.fit_transform(labelList)
print(Y)

[[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]


In [7]:
#sklearn实现
#sklearn.tree.DecisionTreeClassifier 详细说明: https://www.cnblogs.com/hgz-dm/p/10886368.html
clf = tree.DecisionTreeClassifier(criterion= "entropy")#使用Id3
clf = clf.fit(X,Y)
print(clf)
with open("C:/Users/22197/Desktop/tree.dot","w") as f:
        f = tree.export_graphviz(clf,feature_names = vec.get_feature_names(),out_file= f)#使用export_graphviz

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')


In [12]:
import graphviz #导入决策树可视化模块
dot_data = tree.export_graphviz(clf, out_file=None) #以DOT格式导出决策树
graph = graphviz.Source(dot_data)
graph.render(r'C:/Users/22197/Desktop/tree')


'C:/Users/22197/Desktop\\tree.pdf'

In [40]:
#以下是自己实现
#只适用于二分类
#只适用于二分类
#只适用于二分类
#只适用于二分类
#只适用于二分类
#只适用于二分类

In [35]:
labels

['色泽', '根蒂', '敲击', '纹理', '脐部', '触感']

In [36]:
dataSet

[['青绿', '蜷缩', '浊响', '清晰', '凹陷', '硬滑', '好瓜'],
 ['乌黑', '蜷缩', '沉闷', '清晰', '凹陷', '硬滑', '好瓜'],
 ['乌黑', '蜷缩', '浊响', '清晰', '凹陷', '硬滑', '好瓜'],
 ['青绿', '蜷缩', '沉闷', '清晰', '凹陷', '硬滑', '好瓜'],
 ['浅白', '蜷缩', '浊响', '清晰', '凹陷', '硬滑', '好瓜'],
 ['青绿', '稍蜷', '浊响', '清晰', '稍凹', '软粘', '好瓜'],
 ['乌黑', '稍蜷', '浊响', '稍糊', '稍凹', '软粘', '好瓜'],
 ['乌黑', '稍蜷', '浊响', '清晰', '稍凹', '硬滑', '好瓜'],
 ['乌黑', '稍蜷', '沉闷', '稍糊', '稍凹', '硬滑', '坏瓜'],
 ['青绿', '硬挺', '清脆', '清晰', '平坦', '软粘', '坏瓜'],
 ['浅白', '硬挺', '清脆', '模糊', '平坦', '硬滑', '坏瓜'],
 ['浅白', '蜷缩', '浊响', '模糊', '平坦', '软粘', '坏瓜'],
 ['青绿', '稍蜷', '浊响', '稍糊', '凹陷', '硬滑', '坏瓜'],
 ['浅白', '稍蜷', '沉闷', '稍糊', '凹陷', '硬滑', '坏瓜'],
 ['乌黑', '稍蜷', '浊响', '清晰', '稍凹', '软粘', '坏瓜'],
 ['浅白', '蜷缩', '浊响', '模糊', '平坦', '硬滑', '坏瓜'],
 ['青绿', '蜷缩', '沉闷', '稍糊', '稍凹', '硬滑', '坏瓜']]

In [68]:
# 计算信息熵
# data: [1,2,4,5] 样本的序号
def computeEnt(data):
    num = 0
    for i in data:
        num += Y[i]
    p = num/len(data)
    if p == 0 or p == 1:
        return 0
    return -(p*np.log2(p)+(1-p)*np.log2(1-p))
    

In [69]:
labels

['色泽', '根蒂', '敲击', '纹理', '脐部', '触感']

In [91]:
# # 计算信息增益
# data: [1,2,4,5] 样本的序号
# attr: 类型:int，labels[attr]表示在此属性下计算信息增益
def computeGain(data, attr):
    ent = computeEnt(data)
    group = {}
    for i in data:
        if dataSet[i][attr] not in group:
            group[dataSet[i][attr]] = [i]
        else:
            group[dataSet[i][attr]].append(i)
#     print(group) # {'沉闷': [1, 8], '浊响': [5, 6, 11, 15], '清脆': [10]}
    
    for key in group:
        ent -= len(group[key])/len(data)*computeEnt(group[key])
#     print(ent)
    return ent
# for i in range(6):
#     computeGain([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],1)

In [ ]:
import copy
# 用于labels的浅拷贝
# b=copy.copy(a)

In [141]:
# 选择最佳划分属性
# data 同上
# attrList: [0,1,2,3,4] 代表候选属性
def chooseBestAttr(data, attrList):
    attrBest = -1 # 记录最佳属性
    entBest = -1 # 记录最大信息增益
    for i in range(len(attrList)):
        ent = computeGain(data, attrList[i])
        if ent > entBest:
            entBest = ent
            attrBest = attrList[i]
#     print(attrBest, entBest)
    #经过该节点后返回剩余侯选属性以及数据
    attrList.remove(attrBest)
    return attrBest, attrList

chooseBestAttr([i for i in range(17)],[i for i in range(6)])

(3, [0, 1, 2, 4, 5])

In [150]:
# 选择最佳划分属性
# data 同上
# attrList: [0,1,2,3,4] 代表候选属性
def generateTreeID3(data, attrList):
    num = 0
    for i in data:
        num += Y[i][0]
    if num == 0 or num == len(data):# 如果D中样本全为同一类别C，返回
        return {'label':Y[data[0]][0], 'sampleNum':num if num != 0 else len(data)} # 标记为C类
    
    if attrList == []: # A空了却依然不能完整分类  （少了一个D中样本在A上取值相同的判断）
        pos = num # 正例
        neg = len(data) - num # 反例
        return {'label':1,'sampleNum':[pos,neg]} if pos > neg else {'label':0,'sampleNum':[pos,neg]}
        
        
        # 标记为D中分类最多的
    
    attrBest, attrListNew = chooseBestAttr(data, attrList)
    ID3Tree = {labels[attrBest]:{}} # 找到最优划分属性，对属性的每一个取值都再次寻找决策树
#     print(labels[attrBest])
    group = {}
    for i in data: # 对data分割成： {'沉闷': [1, 8], '浊响': [5, 6, 11, 15], '清脆': [10]}
        if dataSet[i][attrBest] not in group:
            group[dataSet[i][attrBest]] = [i]
        else:
            group[dataSet[i][attrBest]].append(i)
    
    for key in group:
        ID3Tree[labels[attrBest]][key] = generateTreeID3(group[key], attrListNew)
        
    
    return ID3Tree
        

In [151]:
ID3 = generateTreeID3([i for i in range(17)], [i for i in range(6)])

In [152]:
print(ID3)

{'纹理': {'清晰': {'根蒂': {'蜷缩': {'label': 1, 'sampleNum': 5}, '稍蜷': {'色泽': {'青绿': {'label': 1, 'sampleNum': 1}, '乌黑': {'触感': {'硬滑': {'label': 1, 'sampleNum': 1}, '软粘': {'label': 0, 'sampleNum': 1}}}}}, '硬挺': {'label': 0, 'sampleNum': 1}}}, '稍糊': {'敲击': {'浊响': {'脐部': {'稍凹': {'label': 1, 'sampleNum': 1}, '凹陷': {'label': 0, 'sampleNum': 1}}}, '沉闷': {'label': 0, 'sampleNum': 3}}}, '模糊': {'label': 0, 'sampleNum': 3}}}


## 尚未解决
1.部分函数尚不熟悉 
2.只能适用于2分类
3.只实现了ID3
4.如果数据预处理用到了one-hot，那么之后如何判断两个样本之间在某个属性上取值是否相同
5.用graphviz对决策树进行绘制  # https://www.jianshu.com/p/2e71649df8c4
